### ISSUE TITLE
Add support for PHP 5.3+ 

### ISSUE THREAD

**Issue by jinraynor1** [friends-of-reactphp/mysql#103]
ReactPHP home page claims to support legacy php 5.3 but this mysql package does not support it.
-  is there a chance to add support in a different branch or tag it as an older release?
- Do you recommend fork this project and adapt it so it can run on older php versions

I know i should not use such an old php version but some of us  have no another option.

**Comment by clue** [comment]
ReactPHP does still support legacy PHP 5.3 just fine. This package here is not part of ReactPHP, but maintained by an independent https://github.com/friends-of-reactphp organization.

We chose not to support PHP 5.3 in this package due to the low demand and the additional implementation constraints imposed by this legacy PHP version.

If you feel this really worth it and feel like sponsoring this development, let me know and I'm happy to assist and/or help review your changes.

Other than that, I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by jinraynor1** [comment]
Hi it seems very few changes if i use  v0.3.3
Sadly i have problems using version v0.4.0 because it uses react/promise: ^2.7 which is only PHP5.4.

Do you have any recommendation on which build start from?

**Comment by clue** [comment]
You should be able to install `react/promise: ^2.7 || ^1.21` for most common use cases.
