### ISSUE TITLE
Is there 10.4.17-MariaDB compatibility?

### ISSUE THREAD

**Issue by carliedu** [friends-of-reactphp/mysql#127]
I'm having connection problems.
I used the more simple example (quick start) too, with no password and default test database, without success.
I always get the message:
[Connection to localhost:3306 failed: Last error for IPv4: Connection to tcp://127.0.0.1:3306?hostname=localhost failed: Connection refused. Previous error for IPv6: Connection to tcp://[::1]:3306?hostname=localhost failed: Connection refused]

**Comment by carliedu** [comment]
I found a comment in code of TcpConnector.php that says:
                // The following hack looks like the only way to
                // detect connection refused errors with PHP's stream sockets.

**Comment by carliedu** [comment]
If it can help, in TcpConnector.php, method connect(), this:
`if (false === \stream_socket_get_name($stream, true)) {` occurs, this means that stream_socket_get_name is returning FALSE.

**Comment by carliedu** [comment]
Looking at php.net documentation of function `stream_socket_get_name`, there is a user comment:
`Surprisingly, on my Linux system, when connected to a localhost service using IPV4, stream_get_socket_name returns ::1 as the peer or local address. One would expect to get localhost or 127.0.0.1 but the ::1 IPV6 localhost is returned instead.`

**Comment by clue** [comment]
@carliedu Thanks for reporting.

This project works just with with MySQL and MariaDB because they both share the exact same protocol.

Here's how you can verify this by running the test suite against a local test database in a Docker container:

```
$ docker run -it --rm --net=host     -e MYSQL_RANDOM_ROOT_PASSWORD=yes -e MYSQL_DATABASE=test     -e MYSQL_USER=test -e MYSQL_PASSWORD=test mariadb:10.4.17
$ vendor/bin/phpunit
```

---

The problem you're seeing doesn't seem to be related to this project, but rather a misconfiguration.

The error message `Connection to localhost:3306 failed: Last error for IPv4: Connection to tcp://127.0.0.1:3306?hostname=localhost failed: Connection refused. Previous error for IPv6: Connection to tcp://[::1]:3306?hostname=localhost failed: Connection refused` suggests this project can not connect to `localhost:3306` which is the default listen address for MySQL/MariaDB on your local machine.

Are you sure your database is running on your local system and there's no firewall preventing incoming connections? You should be able to verify this with any database client, e.g. PHP's PDO or the `mysql` command line client.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always keep discussing and/or reopen this :+1:

**Comment by carliedu** [comment]
@clue, you are right. 
`root@aws:/usr/local/src/clueMysql# telnet localhost 3306
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
root@aws:/usr/local/src/clueMysql# Trying 127.0.0.1...
Trying: command not found
root@aws:/usr/local/src/clueMysql# `
I never thought of testing this, because everything is on the same machine, and in addition, a PHP program with mysqli_ function are working.
I will look why. When I find the problem I write it here.

**Comment by clue** [comment]
If the connection with PDO works, it might be because it's actually using a Unix domain socket path when you're specifying `localhost` as per https://www.php.net/manual/en/ref.pdo-mysql.connection.php#refsect1-ref.pdo-mysql.connection-notes and https://www.php.net/manual/en/ref.pdo-mysql.php#ini.pdo-mysql.default-socket.

Perhaps you can check this setting and see if connections to this socket path work? You can also check your MariaDB server configuration to see what path/address it's listening on.

**Comment by carliedu** [comment]
Only as domumentation for other users:
Here we have a little more things not very well explained:
In php.net documentation at https://www.php.net/manual/en/mysqli.quickstart.connections.php, we can read following:
The hostname localhost has a special meaning. It is bound to the use of Unix domain sockets. **It is not possible to open a TCP/IP connection** using the hostname **localhost** you **must use 127.0.0.1** instead.
I tested 3 situations with PHP's funtion mysqli_connect():
1) mysqli_connect( 'localhost', 'testUser', '' ); --> could connect and read the 2 regs
2) mysqli_connect( '127.0.0.1', 'testUser', '' ); --> Connection REFUSED
3) mysqli_connect( '172.31.1.1', 'testUser', '' ); --> Connection REFUSED
So, in practice, the opposite of what is in the documentation is occurring with mysqli_connect function.

**Comment by carliedu** [comment]
I discovered that MariaDB has a parameter in my.cnf that is enabled as default:
`skip-networking`. This parameter must be commented.
After restarting MySQL service, now port 3306 is open.

**Comment by carliedu** [comment]
Still quick-example.php do not work.
Now it don't have the "connection refused", but it shows no records.
I tried with `127.0.0.1` and `localhost`, without password.
Later I will check what is happening now.
