### ISSUE TITLE
Did not disconnect after second connection

### ISSUE THREAD

**Issue by DangerLifter** [friends-of-reactphp/mysql#6]
Below simple example, which connect/disconnect mysql twice. After second disconnect event loop didn't stop and callback is not called.  "libevent" is used as event loop.

Output is:
$ php ./test
int(1)
int(2)
int(1)

---

``` php
require __DIR__ . '/vendor/autoload.php';

$loop = \React\EventLoop\Factory::create();

$config = array(
    'host'  => '127.0.0.1',
    'port'      => '3306',
    'dbname'    => 'test',
    'user'  => 'root',
    'passwd'    => '',
    'charset'   => 'utf-8',
);

$linkDb = new \React\MySQL\Connection($loop, $config);

$linkDb->connect(function () use ($linkDb) {
    var_dump(1);
    $linkDb->close(function() {
        var_dump(2);
    });
});

$loop->run();

$linkDb->connect(function () use ($linkDb) {
    var_dump(1);
    $linkDb->close(function() {
        var_dump(2);
    });
});

$loop->run();
```

**Comment by clue** [comment]
This is an interesting issue :+1: I've checked the source code and it turns out the interfaces suffer from temporal coupling and `Connection` and other parts are actual stateful in such a way that you can do some nasty things with it, such as:

```php
$connection = new Connection($loop, $config);

// what should this do before a connection is established?
$connection->query('…');

// can we connect twice?
$connection->connect();
$connection->connect();

// can we close twice?
$connection->close();
$connection->close();

// what should this do once the connection is closed again?
$connection->query('…');
```

This also means you probably shouldn't reuse an instance for multiple connections. In your example, you're probably better off using two distinct instances and only invoke `connect()` once on each.

Also, as a rule of thumb, you should probably only ever invoke `$loop->run()` once.
